#! /bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width	2
bspc config window_gap		3
bspc config split_ratio		0.60

bspc config focused_border_color	"#b8bb26"
bspc config normal_border_color		"#3c3836"
bspc config presel_feedback_color	"#fabd2f"
